### PR TITLE
Add a "notes" section to the edit page

### PR DESCRIPTION
**Pull request by theTisch21**
This PR:
Adds a new property to the firebase document "notes"
Adds a parameter to the VALIDATE_FREE_FORM function to mark it optional, and accept `null` strings
Adds a field to the edit page where users can submit notes

### CODE REVIEW

**Review by davidvel25 — APPROVED** [review]
Looks good! If you have extra time (and know how to do it), you could make the text wrap around after it has hit the end of the bounding box, or you can implement a larger bounding box to be more square-like. Otherwise, it looks great!

**Review by daniel-sudz — COMMENTED** [review]
@theTisch21 you need to rebase off of master and resolve conflicts: your files are behind by 2 commits

**Comment by theTisch21** [comment]
@daniel-sudz 
I'm not sure what happened, but it looks like it did something that hopefully deals with any merge conflicts.

**Comment by Zjjc123** [comment]
@theTisch21 I'm giving you write access. Next time you can just make a new branch.

**Comment by daniel-sudz** [comment]
> @theTisch21 I'm giving you write access. Next time you can just make a new branch.

@Zjjc123 that doesn't help with anything -- it's a branch that was behind and not fast-forwarded before changes were made.

**Comment by Zjjc123** [comment]
Oh this is unrelated to the issue. I just didn't know where to tell him that I gave him write

**Comment by theTisch21** [comment]
@daniel-sudz @Zjjc123 I don't see the merge conflicts on my end. Would it be easier if I made a new branch based on `master`, cherry picked my commits over to the new branch, then made a new PR?

**Comment by theTisch21** [comment]
> @theTisch21 I'm giving you write access. Next time you can just make a new branch.

Thanks for write access!

**Review by Zjjc123 — APPROVED** [review]
We probably need to fix up the UI it's so ugly right now. But your changes look good to me but @daniel-sudz should check on it.

**Comment by Zjjc123** [comment]
@theTisch21 I don't see a merge issue. I think @daniel-sudz was talking about the issue before you fixed it.

**Comment by theTisch21** [comment]
I don't see a merge issue either, and github says I can automatically merge, so I'm gonna do that. @daniel-sudz if you see a problem, you can undo this merge.

**Pull request merged**
