### PR TITLE
Recasing Through VSCode

### LINKED ISSUE #124: Keep a consistent capitlization in the repo folder names
I vote for all lower case @daniel-sudz 

can use command `git config core.ignorecase false` to keep track of capitalization to fix name

### PR DESCRIPTION
**Pull request by Zjjc123**
Recapitalization of everything through vscode to make sure all imports are correctly renamed.

`Actions` => `actions`

`Docs` => `docs`

`Firebase` => `firebase`

`ReportGeneration` => `report-generation`

Changing reference in README.md (prettier updated the readme automatically)

Fixed references in workflows

Fixing bad format from #158 

closes #124

### CODE REVIEW

**Comment by Zjjc123** [comment]
Builds are passing just Netlify is broken

**Comment by theTisch21** [comment]
Oops, sorry about the bad formatting on my pr. Thanks for the catch!

**Comment by Zjjc123** [comment]
> Oops, sorry about the bad formatting on my pr. Thanks for the catch!

I only caught that because of daniels new ci prettier test :) it's pretty nice ngl. Vscode has an option to format on save. I'm not sure about jetbrain but probably has similar functions.

**Comment by theTisch21** [comment]
> > Oops, sorry about the bad formatting on my pr. Thanks for the catch!
> 
> I only caught that because of daniels new ci prettier test :) it's pretty nice ngl. Vscode has an option to format on save. I'm not sure about jetbrain but probably has similar functions.

I found that feature and I've enabled it. Thanks!

**Comment by Zjjc123** [comment]
> > > Oops, sorry about the bad formatting on my pr. Thanks for the catch!
> > 
> > I only caught that because of daniels new ci prettier test :) it's pretty nice ngl. Vscode has an option to format on save. I'm not sure about jetbrain but probably has similar functions.
> 
> I found that feature and I've enabled it. Thanks!

Make sure you are using prettier instead of a default formatter there might be slight differences

**Review by daniel-sudz — APPROVED** [review]
can't follow anything since it's auto-generated but probably it's good. Need to also check that firebase functions still compile.

**Pull request merged**
