### PR TITLE
Adding Export Button to Table

### LINKED ISSUE #121: [ADMIN] CSV Export Button
Add a button to export csv from local data

### PR DESCRIPTION
**Pull request by Zjjc123**
Adding an export to csv button in each table. Each user now will be able to export their table as a csv file (easily viewed in excel).

closes #121

### CODE REVIEW

**Comment by theTisch21** [comment]
I do not see this feature on my hours page in the preview app generated by the netlify bot. Is this a feature only for admins?
image

**Comment by theTisch21** [comment]
@Zjjc123 
I can't sign in to the testing app to test this feature, as when I try, firebase redirects me to the official app. How do I sign into the testing app?

**Comment by Zjjc123** [comment]
> @Zjjc123
> I can't sign in to the testing app to test this feature, as when I try, firebase redirects me to the official app. How do I sign into the testing app?

@theTisch21 
Daniel made it so the redirect dynamically changes depend on whether is production or not. So if you run a local instance it should work?
WEIRD THING: You have to remove the `https://` in localhost redirect. I don't know if that is your issue or not?

**Comment by daniel-sudz** [comment]
@theTisch21 the deploy preview urls are quite random so we hard coded the production URL redirect link. You can modify the redirect link by changing it dynamically to the current url window like so https://developer.mozilla.org/en-US/docs/Web/API/Location/origin (ctr+f for localhost and you should be able to find where the prod url is defined)

**Comment by Zjjc123** [comment]
Oh you meant the netlify. I've never really used that since the repo was private until very recently and I didn't have access. But we should probably figure that out.

**Comment by theTisch21** [comment]
Changing the redirect url did the trick. It exported my hours successfully:
image
This feature will be handy!

**Review by theTisch21 — APPROVED** [review]

**Comment by daniel-sudz** [comment]
@Zjjc123 use a proper escaping library like the one in the firebase folder. Be using quotes you are not necessarily generating valid csv and it could break.

**Pull request merged**
