### PR TITLE
Making Root Folder Lower Case

### LINKED ISSUE #124: Keep a consistent capitlization in the repo folder names
I vote for all lower case @daniel-sudz 

can use command `git config core.ignorecase false` to keep track of capitalization to fix name

### PR DESCRIPTION
**Pull request by Zjjc123**
Closes #124

### CODE REVIEW

**Comment by Zjjc123** [comment]
Just need to change the capitalization of the workflows as well.

**Comment by Zjjc123** [comment]
# Result: 
### Root
image

### Firebase
image

**Comment by Zjjc123** [comment]
IMO much more clean

**Review by daniel-sudz — COMMENTED** [review]
I would camel case everything instead of ```report-generation``` it's kind of jarring. Also this breaks os-compatibility because some os take into account case-sensistive names in our build scripts

**Comment by Zjjc123** [comment]
> I would camel case everything instead of `report-generation` it's kind of jarring. Also this breaks os-compatibility because some os take into account case-sensistive names in our build scripts

`report-generation` => `reports`

And change build script. There aren't that many spots that we need to change. I just don't want to change it before we merge.

**Comment by Zjjc123** [comment]
@daniel-sudz also should we all use the same auto formatter on vscode. that would help with consistency? can we enforce that through .vscode

**Comment by daniel-sudz** [comment]
@Zjjc123 no don't commit a ```.vscode``` file. I'm going to add prettier to the root of the repo with a CI check and then it will up to PR's to make sure they have the proper extensions configured for prettier.

**Comment by Zjjc123** [comment]
Merge and change build script?

**Comment by daniel-sudz** [comment]
> `report-generation` => `reports` not a big fan of camel case in the root folder

Seems to be that most people use dashes so alright fine by me
see: https://github.com/microsoft/FluidFramework/tree/main/tools

**Comment by daniel-sudz** [comment]
> And change build script. There aren't that many spots that we need to change. I just don't want to change it before we merge.

There's a lot more than just build scripts that you need to change. There's a bunch of js files that link to that folder. I'm not sure what setup you have in vscode but for me when you rename a folder inside of vscode it automatically changes the imports of all linked files (you might to tweak with your vscode to get this to work). 

This would be the safest way to make sure you don't miss anything

**Comment by Zjjc123** [comment]
> > And change build script. There aren't that many spots that we need to change. I just don't want to change it before we merge.
> 
> There's a lot more than just build scripts that you need to change. There's a bunch of js files that link to that folder. I'm not sure what setup you have in vscode but for me when you rename a folder inside of vscode it automatically changes the imports of all linked files (you might to tweak with your vscode to get this to work).
> 
> This would be the safest way to make sure you don't miss anything

I'm not sure my vscode does anything other than renaming it.

**Comment by daniel-sudz** [comment]
> I'm not sure my vscode does anything other than renaming it.

You might have an old version of vscode https://stackoverflow.com/a/44965566

**Comment by Zjjc123** [comment]
> > I'm not sure my vscode does anything other than renaming it.
> 
> You might have an old version of vscode https://stackoverflow.com/a/44965566

I'm not sure it does anything to the root folder. I don't think we ever import across root folders or referencing the root folders. These are just for imports within the root folders which I'm assuming have relative paths?

**Comment by Zjjc123** [comment]
But this PR is out of date with the new PR merged into master

**Comment by Zjjc123** [comment]
Apparently there are some 
image

**Comment by Zjjc123** [comment]
I'm going to remake this

**Pull request closed without merging**
