### PR TITLE
Changed submit/edit page layout #170

### PR DESCRIPTION
**Pull request by TimofeiK27**
Made the submit/edit page fit on the screen (no scrolling). Kept mobile UI.

### CODE REVIEW

**Review by daniel-sudz — CHANGES_REQUESTED** [review]
@TimofeiK27 what editor did you use? Could you either run ```format-write``` in the root of the repository after installing with ```yarn``` or download the prettier extension for your given IDE and configure it to format on save?

**Comment by TimofeiK27** [comment]
@daniel-sudz I used Visual Studio. I just downloaded Visual Studio Web Development (I hope that's the right thing). I ran the command "yarn format-write" in the root, so I hope it's going to work now!

**Comment by TimofeiK27** [comment]
@daniel-sudz Do I just make a new pull request with the new code?

**Comment by Zjjc123** [comment]
> @daniel-sudz Do I just make a new pull request with the new code?

Just add more commits to your branch and it should automatically update the PR. 
Sorry I have been super busy recently havent had the time to look at the pr

**Comment by Zjjc123** [comment]
Also did you run yarn in the root folder? I don't think you need to do that right @daniel-sudz. there are a bunch of new dependencies in the root folder

**Comment by TimofeiK27** [comment]
@Zjjc123 Ya sorry about that. Can I just revert the yarn file to the previous state?

**Review by daniel-sudz — APPROVED** [review]
Resizes perfectly on mobile and desktop. Thanks! @TimofeiK27

**Pull request merged**
