### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by daniel-sudz**
#145 @Zjjc123 do you want to also be CC'd on PR's?

### CODE REVIEW

**Comment by daniel-sudz** [comment]
Closes #145 forgot

**Comment by Zjjc123** [comment]
> #145 @Zjjc123 do you want to also be CC'd on PR's?

Yeah that would be great

**Comment by daniel-sudz** [comment]
@Zjjc123 g2g?

**Review by Zjjc123 — APPROVED** [review]
g2g

**Pull request merged**
