### PR TITLE
Add the .idea folder to gitignore

### PR DESCRIPTION
**Pull request by theTisch21**
I'm using WebStorm to edit this project, and as a JetBrains IDE, it has files in a folder named .idea that do not need to be committed. This PR will add that folder to the .gitignore, preventing those files from accidentally being committed.

### CODE REVIEW

**Comment by theTisch21** [comment]
Oh yikes! My changes to a different branch made it here... Give me a moment to fix that.

**Comment by theTisch21** [comment]
Other commits have been reverted. Please disregard them.

**Comment by daniel-sudz** [comment]
@theTisch21 I think you reverted all of your changes as this PR has no files changed. You might want to cherry-pick commit 3d964a6d7734d323be9f989291af40054af93561

**Comment by theTisch21** [comment]
@daniel-sudz That should do it. Thanks for the catch!

**Review by daniel-sudz — APPROVED** [review]
All good 👍

**Pull request merged**
