### PR TITLE
Make security rules more strict

### LINKED ISSUE #179: Prevent Squatting of Unverified Email Addresses
https://firebase.google.com/docs/reference/rules/rules.firestore.Request
```
`email` | The email address associated with the account, if present.
-- | --
`email_verified` | `true` if the user has verified they have access to the `email` address.
`phone_number` | The phone number associated with the account, if present.
`name` | The user's display name, if set.
`sub` | The user's Firebase UID. This is unique within a project.
`firebase.identities` | A map of all the identities that are associated with this user's account. The keys of the map can be any of the following: `email`, `phone`, `google.com`, `facebook.com`, `github.com`, `twitter.com`. The values of the map are lists of unique identifiers for each identitity provider associated with the account. For example, `request.auth.token.firebase.identities["google.com"][0]` contains the first Google user ID associated with the account.
`firebase.sign_in_provider` | The sign-in provider used to obtain this token. Can be one of the following strings: `custom`, `password`, `phone`, `anonymous`, `google.com`, `facebook.com`, `github.com`, `twitter.com`.
```

We currently check firestore security rules with ```request.auth.token.email```. However, an external user can simulate regular email/password auth and begin writing to a chosen email address that they may not own. They will retain access until the actual email owners resets their password. 

# Proposal

## Before Change
```request.auth.token.email === emailVariable```

## After 
```request.auth.token.email === emailVariable && request.auth.token.email_verified```

### PR DESCRIPTION
**Pull request by daniel-sudz**
Closes #179 

- Requires email to be verified 
- Allows only password-based auth (in case of misconfiguration)
- Removed rule permitting all users to read report summaries (admin only)
- Updated unit tests for more coverage of test cases

Someone check that access still works in prod when this gets merged. 

image

### CODE REVIEW

**Review by Zjjc123 — COMMENTED** [review]
Do we need to fix /report and /reports?

**Review by Zjjc123 — APPROVED** [review]
I'll work on the client changes for `/reports` and move it into admin

**Comment by daniel-sudz** [comment]
> Do we need to fix /report and /reports?

yes

**Comment by theTisch21** [comment]
@daniel-sudz 
I can confirm, I still have access to my account and can edit/submit service in production

**Pull request merged**
